1.Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга 
(ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. 
Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату 
(то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная).
Произвести расчет как с использованием intercept, так и без.

In [ ]:
import numpy as np

In [ ]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
X

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [ ]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [ ]:
n = len(X)
n

10

In [ ]:
b = (np.mean(X*y)-np.mean(X)*np.mean(y))/(np.mean(X**2)-np.mean(X)**2)
b

2.620538882402765

In [ ]:
a = np.mean(y) - b * np.mean(X)
a

444.1773573243596

без интерсепта

In [ ]:
X = X.reshape((10, 1))
X

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

y = y.reshape((10, 1))
y

In [ ]:
B = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T @ y)
B

array([5.88982042])

с интерсептом (матричный метод)

In [ ]:
X = np.hstack([np.ones((10,1)), X])
X

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [ ]:
B = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T @ y)
B

array([444.17735732,   2.62053888])

2. Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [ ]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
X

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [ ]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [ ]:
def mse_(B1, y=y, X=X, n=10):
  return np.sum((B1 * X - y) ** 2) / n

In [ ]:
B1 = 0.1

In [ ]:
alpha = 1e-6
alpha

1e-06

In [ ]:
for i in range (10000):
  B1 -= alpha * (2 / n) * np.sum((B1 * X - y) * X)
  if i % 5000 == 0:
    print ('Iteration: {i}, B1 = {B1}, mse = {mse}'.format(i = i, B1 = B1, mse = mse_(B1)))

Iteration: 0, B1 = 0.25952808, mse = 493237.7212546963
Iteration: 5000, B1 = 5.889820420132673, mse = 56516.85841571943


*3. Произвести вычисления как в пункте 2, но с вычислением intercept. Учесть, что изменение коэффициентов должно производиться
на каждом шаге одновременно (то есть изменение одного коэффициента не должно влиять на изменение другого во время одной итерации).

In [ ]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
X

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [ ]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [ ]:
B0 = 0.1

In [ ]:
B1 = 0.1

In [ ]:
def mse_(B0, B1, y=y, X=X, n=10):
  return np.sum((B0 + B1 * X - y) ** 2) / n

In [ ]:
alpha = 5e-5
alpha

5e-05

In [ ]:
for i in range (750000):
  B0 -= alpha * (2 / n) * np.sum((B0 * X - y))
  B1 -= alpha * (2 / n) * np.sum((B1 * X - y) * X)
  if i % 30000 == 0:
    print ('Iteration: {i}, B0 = {B0}, B1 = {B1}, mse = {mse}'.format(i = i, B0 = B0, B1 = B1, mse = mse_(B0, B1)))

Iteration: 0, B0 = 7.000986193291719, B1 = 5.889820420132694, mse = 54988.23905866428
Iteration: 30000, B0 = 7.000986193293842, B1 = 5.889820420132689, mse = 54988.239058663836
Iteration: 60000, B0 = 7.000986193293842, B1 = 5.889820420132689, mse = 54988.239058663836
Iteration: 90000, B0 = 7.000986193293842, B1 = 5.889820420132689, mse = 54988.239058663836
Iteration: 120000, B0 = 7.000986193293842, B1 = 5.889820420132689, mse = 54988.239058663836
Iteration: 150000, B0 = 7.000986193293842, B1 = 5.889820420132689, mse = 54988.239058663836
Iteration: 180000, B0 = 7.000986193293842, B1 = 5.889820420132689, mse = 54988.239058663836
Iteration: 210000, B0 = 7.000986193293842, B1 = 5.889820420132689, mse = 54988.239058663836
Iteration: 240000, B0 = 7.000986193293842, B1 = 5.889820420132689, mse = 54988.239058663836
Iteration: 270000, B0 = 7.000986193293842, B1 = 5.889820420132689, mse = 54988.239058663836
Iteration: 300000, B0 = 7.000986193293842, B1 = 5.889820420132689, mse = 54988.2390586638